app:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/code
  links:
    - mongodb
mongodb:
  image: mongo:latest
  ports:
    - "27017:27017"
  volumes:
    - /data/docker/mongo/db:/data/db
  command: mongod --storageEngine=wiredTiger